name: Active Learning Pipeline

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight (UTC). Adjust as needed.
  workflow_dispatch: # Allows manual triggering

jobs:
  active-learning:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Use the version compatible with your scripts

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Active Learning Pipeline
      env:
        CVAT_USER: ${{ secrets.CVAT_USER }}
        CVAT_PASSWORD: ${{ secrets.CVAT_PASSWORD }}
        CVAT_PROJECT_ID: ${{ secrets.CVAT_PROJECT_ID }}
        MODEL_PATH: ${{ secrets.MODEL_PATH }}
      run: |
        python main.py
